language: node_js
sudo: false
node_js:
  - 8
  - 10

services:
  - mongodb

env:
  global:
    - MONGODB_VERSION=2.6.10

before_install:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
  - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
  - mkdir -p data/db
  - mongod --dbpath=data/db > /dev/null 2>&1 &
  - sleep 3

branches:
  only:
    - master
  
before_script:
  - npm install

script:
  - npm test